CRITICAL - 2022-08-28 06:57:23 --> syntax error, unexpected '=', expecting ')'
in APPPATH\Controllers\Usuario.php on line 30.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('Usuario/insertaNuevoUsuario')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('Usuario/insertaNuevoUsuario')
 3 SYSTEMPATH\CodeIgniter.php(779): CodeIgniter\Router\Router->handle('Usuario/insertaNuevoUsuario')
 4 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-28 06:57:57 --> syntax error, unexpected ':'
in APPPATH\Controllers\Usuario.php on line 37.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('Usuario/crearUsuario')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('Usuario/crearUsuario')
 3 SYSTEMPATH\CodeIgniter.php(779): CodeIgniter\Router\Router->handle('Usuario/crearUsuario')
 4 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-28 06:58:02 --> syntax error, unexpected ':'
in APPPATH\Controllers\Usuario.php on line 37.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('Usuario/crearUsuario')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('Usuario/crearUsuario')
 3 SYSTEMPATH\CodeIgniter.php(779): CodeIgniter\Router\Router->handle('Usuario/crearUsuario')
 4 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-28 06:58:18 --> syntax error, unexpected ':'
in APPPATH\Controllers\Usuario.php on line 37.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('Usuario/crearUsuario')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('Usuario/crearUsuario')
 3 SYSTEMPATH\CodeIgniter.php(779): CodeIgniter\Router\Router->handle('Usuario/crearUsuario')
 4 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-28 06:58:42 --> mysqli_sql_exception: Column 'rut' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(39): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 07:00:16 --> mysqli_sql_exception: Column 'rut' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(39): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-08-28 07:00:16 --> Call to undefined method App\Models\UsuarioModel::erros
in SYSTEMPATH\Model.php on line 773.
 1 APPPATH\Controllers\Usuario.php(41): CodeIgniter\Model->__call('erros', [])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-28 07:01:22 --> mysqli_sql_exception: Column 'rut' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(39): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 07:05:31 --> mysqli_sql_exception: Column 'rut' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 07:05:49 --> mysqli_sql_exception: Column 'rut' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 07:08:16 --> mysqli_sql_exception: Column 'rut' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(42): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 07:12:14 --> mysqli_sql_exception: Column 'rut' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 07:13:16 --> mysqli_sql_exception: Column 'rut' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 07:14:05 --> mysqli_sql_exception: Column 'rut' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 07:14:44 --> mysqli_sql_exception: Column 'rut' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(42): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 07:19:26 --> mysqli_sql_exception: Column 'rut' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(42): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 07:22:36 --> mysqli_sql_exception: Column 'id_tipoUsuario' cannot be null in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(42): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-08-28 07:23:16 --> Call to a member function getPost() on null
in APPPATH\Controllers\Usuario.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-28 07:33:02 --> Call to a member function getPost() on null
in APPPATH\Controllers\Usuario.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-28 07:34:07 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`minuevabasededatos`.`usuarios`, CONSTRAINT `FK_usuarios_tipousuarios` FOREIGN KEY (`id_tipoUsuario`) REFERENCES `tipousuarios` (`id_tipoUsuarios`)) in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(38): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 07:56:07 --> mysqli_sql_exception: Duplicate entry '6531783' for key 'Índice 2' in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(38): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-08-28 09:42:32 --> Argument 2 passed to CodeIgniter\Validation\Rules::is_unique() must be of the type string, null given, called in C:\xampp\htdocs\miProyecto\system\Validation\Validation.php on line 307
in SYSTEMPATH\Validation\Rules.php on line 126.
 1 SYSTEMPATH\Validation\Validation.php(307): CodeIgniter\Validation\Rules->is_unique('6531783', null)
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('rut', 'rut', '6531783', [...], [...])
 3 SYSTEMPATH\BaseModel.php(1350): CodeIgniter\Validation\Validation->run([...], null, null)
 4 SYSTEMPATH\BaseModel.php(707): CodeIgniter\BaseModel->validate([...])
 5 SYSTEMPATH\Model.php(666): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Usuario.php(38): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-28 09:42:51 --> Argument 2 passed to CodeIgniter\Validation\Rules::is_unique() must be of the type string, null given, called in C:\xampp\htdocs\miProyecto\system\Validation\Validation.php on line 307
in SYSTEMPATH\Validation\Rules.php on line 126.
 1 SYSTEMPATH\Validation\Validation.php(307): CodeIgniter\Validation\Rules->is_unique('6531783', null)
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('rut', 'rut', '6531783', [...], [...])
 3 SYSTEMPATH\BaseModel.php(1350): CodeIgniter\Validation\Validation->run([...], null, null)
 4 SYSTEMPATH\BaseModel.php(707): CodeIgniter\BaseModel->validate([...])
 5 SYSTEMPATH\Model.php(666): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Usuario.php(90): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-28 09:43:47 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1
WHERE 1 = :1:
 LIMIT 1' at line 2 in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM 1...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM 1...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM 1...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM 1...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\miProyecto\system\Validation\Validation.php(308): CodeIgniter\Validation\Rules->is_unique('6531783', '1', Array, NULL)
#6 C:\xampp\htdocs\miProyecto\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('rut', 'rut', '6531783', Array, Array)
#7 C:\xampp\htdocs\miProyecto\system\BaseModel.php(1350): CodeIgniter\Validation\Validation->run(Array, NULL, NULL)
#8 C:\xampp\htdocs\miProyecto\system\BaseModel.php(707): CodeIgniter\BaseModel->validate(Array)
#9 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#10 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(90): CodeIgniter\Model->insert(Array)
#11 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#12 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#13 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2022-08-28 09:43:47 --> Call to a member function getRow() on bool
in SYSTEMPATH\Validation\Rules.php on line 142.
 1 SYSTEMPATH\Validation\Validation.php(308): CodeIgniter\Validation\Rules->is_unique('6531783', '1', [...], null)
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('rut', 'rut', '6531783', [...], [...])
 3 SYSTEMPATH\BaseModel.php(1350): CodeIgniter\Validation\Validation->run([...], null, null)
 4 SYSTEMPATH\BaseModel.php(707): CodeIgniter\BaseModel->validate([...])
 5 SYSTEMPATH\Model.php(666): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Usuario.php(90): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-28 10:42:29 --> syntax error, unexpected '')' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
in APPPATH\Controllers\Usuario.php on line 74.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('Usuario/crearUsuarioAjax')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('Usuario/crearUsuarioAjax')
 3 SYSTEMPATH\CodeIgniter.php(779): CodeIgniter\Router\Router->handle('Usuario/crearUsuarioAjax')
 4 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-28 10:44:20 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`minuevabasededatos`.`usuarios`, CONSTRAINT `FK_usuarios_tipousuarios` FOREIGN KEY (`id_tipoUsuario`) REFERENCES `tipousuarios` (`id_tipoUsuarios`)) in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(98): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-08-28 10:51:48 --> syntax error, unexpected ''class'' (T_CONSTANT_ENCAPSED_STRING), expecting ']'
in APPPATH\Views\Usuario\crearUsuarioAjax.php on line 8.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Usuario/crearUsuarioAjax', [], true)
 3 APPPATH\Controllers\Usuario.php(80): view('Usuario/crearUsuarioAjax', [...])
 4 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->crearUsuarioAjax()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-28 10:52:05 --> syntax error, unexpected ''class'' (T_CONSTANT_ENCAPSED_STRING), expecting ']'
in APPPATH\Views\Usuario\crearUsuarioAjax.php on line 8.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Usuario/crearUsuarioAjax', [], true)
 3 APPPATH\Controllers\Usuario.php(80): view('Usuario/crearUsuarioAjax', [...])
 4 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->crearUsuarioAjax()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-28 12:11:30 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`minuevabasededatos`.`usuarios`, CONSTRAINT `FK_usuarios_tipousuarios` FOREIGN KEY (`id_tipoUsuario`) REFERENCES `tipousuarios` (`id_tipoUsuarios`)) in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(94): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 12:11:40 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`minuevabasededatos`.`usuarios`, CONSTRAINT `FK_usuarios_tipousuarios` FOREIGN KEY (`id_tipoUsuario`) REFERENCES `tipousuarios` (`id_tipoUsuarios`)) in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(94): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 12:12:45 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`minuevabasededatos`.`usuarios`, CONSTRAINT `FK_usuarios_tipousuarios` FOREIGN KEY (`id_tipoUsuario`) REFERENCES `tipousuarios` (`id_tipoUsuarios`)) in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(94): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 12:17:35 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`minuevabasededatos`.`usuarios`, CONSTRAINT `FK_usuarios_tipousuarios` FOREIGN KEY (`id_tipoUsuario`) REFERENCES `tipousuarios` (`id_tipoUsuarios`)) in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(94): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 12:17:36 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`minuevabasededatos`.`usuarios`, CONSTRAINT `FK_usuarios_tipousuarios` FOREIGN KEY (`id_tipoUsuario`) REFERENCES `tipousuarios` (`id_tipoUsuarios`)) in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(94): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 12:17:36 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`minuevabasededatos`.`usuarios`, CONSTRAINT `FK_usuarios_tipousuarios` FOREIGN KEY (`id_tipoUsuario`) REFERENCES `tipousuarios` (`id_tipoUsuarios`)) in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(94): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-08-28 12:26:56 --> syntax error, unexpected '');' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
in APPPATH\Controllers\Usuario.php on line 69.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('Usuario/crearUsuarioAjax')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('Usuario/crearUsuarioAjax')
 3 SYSTEMPATH\CodeIgniter.php(779): CodeIgniter\Router\Router->handle('Usuario/crearUsuarioAjax')
 4 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-28 12:30:17 --> syntax error, unexpected '''' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
in APPPATH\Controllers\Usuario.php on line 60.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('Usuario/crearUsuarioAjax')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('Usuario/crearUsuarioAjax')
 3 SYSTEMPATH\CodeIgniter.php(779): CodeIgniter\Router\Router->handle('Usuario/crearUsuarioAjax')
 4 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-28 12:49:49 --> syntax error, unexpected '''' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
in APPPATH\Controllers\Usuario.php on line 60.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('Usuario/crearUsuarioAjax')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('Usuario/crearUsuarioAjax')
 3 SYSTEMPATH\CodeIgniter.php(779): CodeIgniter\Router\Router->handle('Usuario/crearUsuarioAjax')
 4 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-28 12:57:34 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`minuevabasededatos`.`usuarios`, CONSTRAINT `FK_usuarios_tipousuarios` FOREIGN KEY (`id_tipoUsuario`) REFERENCES `tipousuarios` (`id_tipoUsuarios`)) in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(95): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 12:57:35 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`minuevabasededatos`.`usuarios`, CONSTRAINT `FK_usuarios_tipousuarios` FOREIGN KEY (`id_tipoUsuario`) REFERENCES `tipousuarios` (`id_tipoUsuarios`)) in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(95): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-08-28 12:58:33 --> syntax error, unexpected '');' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
in APPPATH\Controllers\Usuario.php on line 75.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('Usuario/crearUsuarioAjax')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('Usuario/crearUsuarioAjax')
 3 SYSTEMPATH\CodeIgniter.php(779): CodeIgniter\Router\Router->handle('Usuario/crearUsuarioAjax')
 4 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-28 12:58:52 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`minuevabasededatos`.`usuarios`, CONSTRAINT `FK_usuarios_tipousuarios` FOREIGN KEY (`id_tipoUsuario`) REFERENCES `tipousuarios` (`id_tipoUsuarios`)) in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(99): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-08-28 14:12:01 --> Creating default object from empty value
in APPPATH\Controllers\Usuario.php on line 167.
 1 APPPATH\Controllers\Usuario.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Creating default object from empty value', 'APPPATH\\Controllers\\Usuario.php', 167, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-28 14:12:47 --> Creating default object from empty value
in APPPATH\Controllers\Usuario.php on line 167.
 1 APPPATH\Controllers\Usuario.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Creating default object from empty value', 'APPPATH\\Controllers\\Usuario.php', 167, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-28 14:13:51 --> Creating default object from empty value
in APPPATH\Controllers\Usuario.php on line 167.
 1 APPPATH\Controllers\Usuario.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Creating default object from empty value', 'APPPATH\\Controllers\\Usuario.php', 167, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-28 17:57:09 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(163): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuarioAjax()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-08-28 17:59:18 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\miProyecto\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\miProyecto\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\miProyecto\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\miProyecto\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miProyecto\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miProyecto\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(38): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#9 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#10 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-08-28 18:03:43 --> Cannot redeclare App\Models\UsuarioModel::$createdField
in APPPATH\Models\UsuarioModel.php on line 21.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
